### PR TITLE
Adding PentesterLab

### PR DESCRIPTION
**Pull request by snyff**
Hi Friend,

Just adding Pentesterlab :)

Cheers,
Louis

### CODE REVIEW

**Comment by 0xtf** [comment]
@snyff Hi Louis. Happy to merge this as soon as you complete the dependencies. Thanks.

**Comment by snyff** [comment]
Hi @0xtf,

I signed it yesterday but it doesn't seem to work. I can see it as signed since yesterday.
Screen Shot 2023-05-30 at 8 24 28 am

Best,
Louis

**Comment by 0xtf** [comment]
It currently has 1 out of 2 signatures. Yours appears as completed. Is someone else supposed to be signing?
image

**Comment by snyff** [comment]
very interesting, No remediate is another github account I have that uses the same ssh key . No one else needs to sign.

**Comment by 0xtf** [comment]
> very interesting, No remediate is another github account I have that uses the same ssh key . No one else needs to sign.

Unfortunately it is a pre-requisite by CLA that I can't overwrite.

**Comment by remediate** [comment]
done :)

**Comment by snyff** [comment]
Thanks :)

**Comment by 0xtf** [comment]
> Thanks :)

NP ;)

**Pull request merged**
