### PR TITLE
Update pledge.html

### PR DESCRIPTION
**Pull request by franksec42**
Phoenix Security Committing pledge

### CODE REVIEW

**Comment by franksec42** [comment]
Phoenix Security Committing pledge

**Comment by curphey** [comment]
The CLA hasnt been signed. Please do that so I can merge.

**Comment by curphey** [comment]
I am also looking at this page. You have a bunch of awards that have been or almost certainly will be nominated and unless you return them I think that will put you in an awkward position https://phoenix.security/about-us/

**Comment by franksec42** [comment]
Referring to computing ?RegardsFrancesco CipolloneDirector NSC42 LtdSent from mobile, apologize for typos On 25 May 2023, at 9:12 AM, Mark Curphey ***@***.***> wrote:﻿
I am also looking at this page. You have a bunch of awards that have been or almost certainly will be nominated and unless you return them I think that will put you in an awkward position https://phoenix.security/about-us/

**Comment by curphey** [comment]
Closing this given https://phoenix.security/about-us/ and no response to comment above. Will re-open if requested.

**Pull request closed without merging**
