### PR TITLE
Tromzo Pledge

### PR DESCRIPTION
**Pull request by corin09**

### CODE REVIEW

**Comment by curphey** [comment]
You also need to update the HTML with your details as per instructions (also in HTML comments on pledge.tml). If you can take care of that I can merge. Many thanks.

**Comment by corin09** [comment]
@curphey - updated in #40 - Hopefully, I did it correctly. Thank you so much!

**Comment by 0xtf** [comment]
@corin09 I would recommend looking at the other entries and do it similarly; no need to change the link properties (also the image path is incorrect). Ideally it should also be done under the same PR (this one), to make it easier to track and merge.

**Comment by corin09** [comment]
Okay, I keep messing it up. I am going to close this PR and open a new one. Sorry :(

**Pull request closed without merging**
